## gz_ros2_control plugin configuration - Provide parameters for spawners
## Controller manager settings only, no controller type declarations

controller_manager:
  ros__parameters:
    use_sim_time: true
    update_rate: 100
    # No controller type declarations here to avoid auto-loading

# Controller parameter blocks (used by spawners)
joint_state_broadcaster:
  ros__parameters:
    use_sim_time: true

ackermann_steering_controller:
  ros__parameters:
    use_sim_time: true
    # Joint names MUST match URDF
    rear_wheels_names: ["rear_left_wheel_joint", "rear_right_wheel_joint"]
    front_steering_names: ["front_left_steer_joint", "front_right_steer_joint"]

    # Geometry
    wheelbase: 0.567            # meters
    front_wheel_track: 0.35     # meters  
    rear_wheel_track: 0.35      # meters
    steering_limit: 0.785398163 # 45 degrees in rad
    speed_limit: 2.0            # m/s

    # Command interface
    cmd_timeout: 0.5            # seconds
    use_stamped_cmd: false      # we publish to .../reference_unstamped

    # Odometry
    enable_odom_tf: true
    odom_frame_id: odom
    base_frame_id: base_footprint
    publish_rate: 50.0
