## gz_ros2_control plugin configuration - Controller type definitions for Gazebo
## Controller manager settings WITH controller type declarations

controller_manager:
  ros__parameters:
    use_sim_time: true
    update_rate: 100
    
    # Controller type declarations (required for Gazebo)
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      
    ackermann_steering_controller:
      type: ackermann_steering_controller/AckermannSteeringController

# Controller parameter blocks (used by spawners)
joint_state_broadcaster:
  ros__parameters:
    use_sim_time: true

ackermann_steering_controller:
  ros__parameters:
    use_sim_time: true
    
    # Updated parameter names for ROS 2 Jazzy
    steering_joints_names: ["front_left_steer_joint", "front_right_steer_joint"]
    traction_joints_names: ["rear_left_wheel_joint", "rear_right_wheel_joint"]
    
    # Wheel and geometry parameters
    traction_wheels_radius: 0.08    # 80mm radius
    steering_track_width: 0.435     # meters (track width)
    traction_track_width: 0.435     # meters (same as steering for this rover)
    wheelbase: 0.567                # meters
    steering_limit: 0.785398163     # 45 degrees in radians
    speed_limit: 2.0                # m/s

    # Command interface
    cmd_timeout: 0.5                # seconds
    use_stamped_cmd: false          # we publish to .../reference_unstamped

    # Odometry
    enable_odom_tf: true
    odom_frame_id: odom
    base_frame_id: base_link
    publish_rate: 50.0
