# Robot localization EKF configuration for rover hardware
# Fuses wheel odometry from ackermann controller with VIPS position data

ekf_filter_node:
  ros__parameters:
    frequency: 30.0
    sensor_timeout: 0.1
    two_d_mode: false
    transform_time_offset: 0.0
    transform_timeout: 0.0
    print_diagnostics: true
    debug: false

    # Frame configuration
    map_frame: map              # VIPS provides map-level positioning
    odom_frame: odom           # EKF will publish map->odom transform
    base_link_frame: base_link # Robot base frame
    world_frame: odom          # Use odom as world frame (can switch to map if needed)

    # Input topics and configuration
    
    # Odometry input from ackermann steering controller (wheel odometry)
    odom0: /ackermann_steering_controller/odometry
    odom0_config: [false, false, false,    # x, y, z position (ignore for wheel odom drift)
                   false, false, false,    # roll, pitch, yaw orientation (ignore)
                   true,  true,  false,    # x_dot, y_dot, z_dot velocity (trust wheel speeds)
                   false, false, true,     # roll_dot, pitch_dot, yaw_dot (trust yaw rate)
                   false, false, false]    # x_ddot, y_ddot, z_ddot acceleration (ignore)
    odom0_queue_size: 5
    odom0_nodelay: false
    odom0_differential: false
    odom0_relative: false

    # VIPS odometry input (high-precision position)
    odom1: /vips/odometry
    odom1_config: [true,  true,  false,    # x, y, z position (trust VIPS position)
                   false, false, true,     # roll, pitch, yaw orientation (trust VIPS heading)
                   false, false, false,    # x_dot, y_dot, z_dot velocity (wheel odom is better)
                   false, false, false,    # roll_dot, pitch_dot, yaw_dot (wheel odom is better)
                   false, false, false]    # x_ddot, y_ddot, z_ddot acceleration (ignore)
    odom1_queue_size: 2
    odom1_nodelay: false
    odom1_differential: false
    odom1_relative: false

    # IMU input from VIPS (if available)
    imu0: /vips/imu
    imu0_config: [false, false, false,     # x, y, z position (IMU doesn't provide position)
                  true,  true,  true,      # roll, pitch, yaw orientation (trust IMU attitude)
                  false, false, false,     # x_dot, y_dot, z_dot velocity (IMU velocity is noisy)
                  true,  true,  true,      # roll_dot, pitch_dot, yaw_dot (trust angular velocities)
                  true,  true,  true]      # x_ddot, y_ddot, z_ddot acceleration (trust IMU accel)
    imu0_nodelay: false
    imu0_differential: false
    imu0_relative: true
    imu0_queue_size: 5
    imu0_remove_gravitational_acceleration: true

    # Advanced parameters
    use_control: false          # Don't use control inputs (cmd_vel)
    stamped_control: false
    control_timeout: 0.2
    control_config: [true, false, false, false, false, true]

    # Process noise covariance (Q)
    # Higher values = more responsive to changes, lower = more stable
    process_noise_covariance: [0.05, 0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
                              0,    0.05, 0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
                              0,    0,    0.06, 0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
                              0,    0,    0,    0.03, 0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
                              0,    0,    0,    0,    0.03, 0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
                              0,    0,    0,    0,    0,    0.06, 0,     0,     0,    0,    0,    0,    0,    0,    0,
                              0,    0,    0,    0,    0,    0,    0.025, 0,     0,    0,    0,    0,    0,    0,    0,
                              0,    0,    0,    0,    0,    0,    0,     0.025, 0,    0,    0,    0,    0,    0,    0,
                              0,    0,    0,    0,    0,    0,    0,     0,     0.04, 0,    0,    0,    0,    0,    0,
                              0,    0,    0,    0,    0,    0,    0,     0,     0,    0.01, 0,    0,    0,    0,    0,
                              0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0.01, 0,    0,    0,    0,
                              0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0.02, 0,    0,    0,
                              0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0.01, 0,    0,
                              0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0.01, 0,
                              0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0.015]

    # Initial estimate error covariance (P0)
    initial_estimate_covariance: [1e-9, 0,    0,    0,    0,    0,    0,    0,    0,    0,     0,     0,     0,    0,    0,
                                 0,    1e-9, 0,    0,    0,    0,    0,    0,    0,    0,     0,     0,     0,    0,    0,
                                 0,    0,    1e-9, 0,    0,    0,    0,    0,    0,    0,     0,     0,     0,    0,    0,
                                 0,    0,    0,    1e-9, 0,    0,    0,    0,    0,    0,     0,     0,     0,    0,    0,
                                 0,    0,    0,    0,    1e-9, 0,    0,    0,    0,    0,     0,     0,     0,    0,    0,
                                 0,    0,    0,    0,    0,    1e-9, 0,    0,    0,    0,     0,     0,     0,    0,    0,
                                 0,    0,    0,    0,    0,    0,    1e-9, 0,    0,    0,     0,     0,     0,    0,    0,
                                 0,    0,    0,    0,    0,    0,    0,    1e-9, 0,    0,     0,     0,     0,    0,    0,
                                 0,    0,    0,    0,    0,    0,    0,    0,    1e-9, 0,     0,     0,     0,    0,    0,
                                 0,    0,    0,    0,    0,    0,    0,    0,    0,    1e-9,  0,     0,     0,    0,    0,
                                 0,    0,    0,    0,    0,    0,    0,    0,    0,    0,     1e-9,  0,     0,    0,    0,
                                 0,    0,    0,    0,    0,    0,    0,    0,    0,    0,     0,     1e-9,  0,    0,    0,
                                 0,    0,    0,    0,    0,    0,    0,    0,    0,    0,     0,     0,     1e-9, 0,    0,
                                 0,    0,    0,    0,    0,    0,    0,    0,    0,    0,     0,     0,     0,    1e-9, 0,
                                 0,    0,    0,    0,    0,    0,    0,    0,    0,    0,     0,     0,     0,    0,    1e-9]
