# ros2_control controller configuration for simulation (gz_ros2_control)
controller_manager:
  ros__parameters:
    use_sim_time: true
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    ackermann_steering_controller:
      type: ackermann_steering_controller/AckermannSteeringController

# Controller-specific parameters
ackermann_steering_controller:
  ros__parameters:
    # Joint names MUST match your URDF
    rear_wheels_names: ["rear_left_wheel_joint", "rear_right_wheel_joint"]
    front_steering_names: ["front_left_steer_joint", "front_right_steer_joint"]

    # Geometry (use your real values)
    wheelbase: 0.567            # from your converter log
    front_wheel_track: 0.35
    rear_wheel_track: 0.35
    steering_limit: 0.785398163 # 45 degrees
    speed_limit: 2.0

    # Command interface
    cmd_timeout: 0.5            # seconds
    use_stamped_cmd: false      # we publish to .../reference_unstamped

    # Odometry
    enable_odom_tf: true
    odom_frame_id: odom
    base_frame_id: base_link
    publish_rate: 50.0