# Configuration for the ros2_control controller manager and controllers - SIMULATION
controller_manager:
  ros__parameters:
    update_rate: 20 # Hz (Reduced from 50 to match Gazebo timing better)
    use_sim_time: true  # SIMULATION uses sim time

    # Timeout and retry settings
    switch_timeout: 5.0
    activate_timeout: 5.0

    # Controller definitions
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    ackermann_steering_controller:
      type: ackermann_steering_controller/AckermannSteeringController

# Parameters for the Ackermann Steering Controller
ackermann_steering_controller:
  ros__parameters:
    use_sim_time: true  # SIMULATION uses sim time
    # These kinematic parameters MUST match the values in the URDF
    wheelbase: 0.567      # 567mm - Updated to match actual rover
    # Updated parameter names for jazzy compatibility
    traction_track_width: 0.435     # 435mm - Updated to match actual rover
    steering_track_width: 0.435     # 435mm - Updated to match actual rover
    traction_wheels_radius: 0.08    # 80mm radius (160mm diameter) - Required parameter
    # Joint names from the URDF (Jazzy ackermann_steering_controller expects these names)
    traction_joints_names:
      - rear_right_wheel_joint
      - rear_left_wheel_joint
    steering_joints_names:
      - front_right_steer_joint
      - front_left_steer_joint
    # Odometry configuration (use velocity/open-loop early to avoid NaNs on startup)
    open_loop: true
    position_feedback: false
    velocity_rolling_window_size: 5
    odom_frame_id: "odom"
    base_frame_id: "base_link"
    publish_rate: 50.0
    enable_odom_tf: true # Enable for simulation (no sensor fusion)

# Parameters for the Joint State Broadcaster
joint_state_broadcaster:
  ros__parameters:
    use_sim_time: true  # SIMULATION uses sim time
    # The list of joints this broadcaster will publish states for
    joints:
      - rear_left_wheel_joint
      - rear_right_wheel_joint
      - front_left_wheel_joint
      - front_right_wheel_joint
      - front_left_steer_joint
      - front_right_steer_joint
