# Configuration for the ros2_control controller manager and controllers - HARDWARE
controller_manager:
  ros__parameters:
    update_rate: 20 # Hz (Stable rate for real hardware)
    use_sim_time: false  # HARDWARE uses wall clock time
    
    # Timeout and retry settings
    switch_timeout: 5.0
    activate_timeout: 5.0
    
    # Controller definitions - Load but don't activate yet
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    ackermann_steering_controller:
      type: ackermann_steering_controller/AckermannSteeringController

# Parameters for the Ackermann Steering Controller
ackermann_steering_controller:
  ros__parameters:
    use_sim_time: false  # HARDWARE uses wall clock time
    # These kinematic parameters MUST match the values in the URDF
    wheelbase: 0.567      # 567mm - Updated to match actual rover
    track_width: 0.435    # 435mm - Updated to match actual rover  
    traction_wheels_radius: 0.08  # 80mm radius (160mm diameter) - Updated to match actual rover

    # Joint names from the URDF (new parameter names)
    traction_joints_names: ["rear_left_wheel_joint", "rear_right_wheel_joint"]
    steering_joints_names: ["front_left_steer_joint", "front_right_steer_joint"]
    
    # Odometry configuration
    open_loop: false
    position_feedback: true
    odom_frame_id: "odom"
    base_frame_id: "base_link"
    publish_rate: 50.0
    enable_odom_tf: false # IMPORTANT: Set to false, robot_localization will publish this TF

# Parameters for the Joint State Broadcaster
joint_state_broadcaster:
  ros__parameters:
    use_sim_time: false  # HARDWARE uses wall clock time
    # The list of joints this broadcaster will publish states for
    joints:
      - rear_left_wheel_joint
      - rear_right_wheel_joint
      - front_left_wheel_joint
      - front_right_wheel_joint
      - front_left_steer_joint
      - front_right_steer_joint
