#!/bin/bash

# Display available scripts and their descriptions
echo "=== Rover ROS2 Workspace Scripts ==="
echo ""
echo "Setup & Build:"
echo "  ./scripts/build.sh                 - Build the entire workspace"
echo "  ./scripts/check_urdf.sh            - Validate URDF with current specifications"
echo ""
echo "Launch Scripts:"
echo "  ./scripts/run_simulation.sh        - Start rover in Gazebo simulation"
echo "  ./scripts/run_real_robot.sh        - Start real rover hardware"
echo ""
echo "Movement Scripts:"
echo "  ./scripts/interactive_control.sh   - Interactive menu for rover control"
echo "  ./scripts/drive_circle.sh          - Make rover drive in a circle"
echo "  ./scripts/drive_figure8.sh         - Make rover drive in figure-8 pattern"
echo "  ./scripts/drive_forward_back.sh    - Make rover drive forward and backward"
echo "  ./scripts/stop_rover.sh            - Stop the rover immediately"
echo ""
echo "Utilities:"
echo "  ./scripts/help.sh                  - Show this help message"
echo ""
echo "📖 For detailed instructions, see README.md"
echo ""
echo "🚀 Quick start:"
echo "   1. ./scripts/build.sh"
echo "   2. ./scripts/run_simulation.sh    (in one terminal)"
echo "   3. ./scripts/interactive_control.sh    (in another terminal)"
